/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
import { NavInfo } from "./components/journal-navigator/journal-navigator";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface JournalMain {
    }
    interface JournalNavigator {
        "navInfo": Array<NavInfo>;
    }
    interface JournalPage {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLJournalMainElement extends Components.JournalMain, HTMLStencilElement {
    }
    var HTMLJournalMainElement: {
        prototype: HTMLJournalMainElement;
        new (): HTMLJournalMainElement;
    };
    interface HTMLJournalNavigatorElement extends Components.JournalNavigator, HTMLStencilElement {
    }
    var HTMLJournalNavigatorElement: {
        prototype: HTMLJournalNavigatorElement;
        new (): HTMLJournalNavigatorElement;
    };
    interface HTMLJournalPageElement extends Components.JournalPage, HTMLStencilElement {
    }
    var HTMLJournalPageElement: {
        prototype: HTMLJournalPageElement;
        new (): HTMLJournalPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "journal-main": HTMLJournalMainElement;
        "journal-navigator": HTMLJournalNavigatorElement;
        "journal-page": HTMLJournalPageElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface JournalMain {
    }
    interface JournalNavigator {
        "navInfo"?: Array<NavInfo>;
    }
    interface JournalPage {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "journal-main": JournalMain;
        "journal-navigator": JournalNavigator;
        "journal-page": JournalPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "journal-main": LocalJSX.JournalMain & JSXBase.HTMLAttributes<HTMLJournalMainElement>;
            "journal-navigator": LocalJSX.JournalNavigator & JSXBase.HTMLAttributes<HTMLJournalNavigatorElement>;
            "journal-page": LocalJSX.JournalPage & JSXBase.HTMLAttributes<HTMLJournalPageElement>;
        }
    }
}
